// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/artist_service_mock.go -package=mocks -source=interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "eventro2/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArtistServiceI is a mock of ArtistServiceI interface.
type MockArtistServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockArtistServiceIMockRecorder
	isgomock struct{}
}

// MockArtistServiceIMockRecorder is the mock recorder for MockArtistServiceI.
type MockArtistServiceIMockRecorder struct {
	mock *MockArtistServiceI
}

// NewMockArtistServiceI creates a new mock instance.
func NewMockArtistServiceI(ctrl *gomock.Controller) *MockArtistServiceI {
	mock := &MockArtistServiceI{ctrl: ctrl}
	mock.recorder = &MockArtistServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtistServiceI) EXPECT() *MockArtistServiceIMockRecorder {
	return m.recorder
}

// CreateArtist mocks base method.
func (m *MockArtistServiceI) CreateArtist(ctx context.Context, name, bio string) (models.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtist", ctx, name, bio)
	ret0, _ := ret[0].(models.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArtist indicates an expected call of CreateArtist.
func (mr *MockArtistServiceIMockRecorder) CreateArtist(ctx, name, bio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtist", reflect.TypeOf((*MockArtistServiceI)(nil).CreateArtist), ctx, name, bio)
}

// DeleteArtist mocks base method.
func (m *MockArtistServiceI) DeleteArtist(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArtist", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArtist indicates an expected call of DeleteArtist.
func (mr *MockArtistServiceIMockRecorder) DeleteArtist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArtist", reflect.TypeOf((*MockArtistServiceI)(nil).DeleteArtist), ctx, id)
}

// GetArtistByID mocks base method.
func (m *MockArtistServiceI) GetArtistByID(ctx context.Context, id string) (*models.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistByID", ctx, id)
	ret0, _ := ret[0].(*models.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistByID indicates an expected call of GetArtistByID.
func (mr *MockArtistServiceIMockRecorder) GetArtistByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistByID", reflect.TypeOf((*MockArtistServiceI)(nil).GetArtistByID), ctx, id)
}

// GetArtists mocks base method.
func (m *MockArtistServiceI) GetArtists(ctx context.Context, name string) ([]models.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtists", ctx, name)
	ret0, _ := ret[0].([]models.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtists indicates an expected call of GetArtists.
func (mr *MockArtistServiceIMockRecorder) GetArtists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtists", reflect.TypeOf((*MockArtistServiceI)(nil).GetArtists), ctx, name)
}
