// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/booking_service_mock.go -package=mocks -source=interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "eventro2/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBookingServiceInterface is a mock of BookingServiceInterface interface.
type MockBookingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockBookingServiceInterfaceMockRecorder is the mock recorder for MockBookingServiceInterface.
type MockBookingServiceInterfaceMockRecorder struct {
	mock *MockBookingServiceInterface
}

// NewMockBookingServiceInterface creates a new mock instance.
func NewMockBookingServiceInterface(ctrl *gomock.Controller) *MockBookingServiceInterface {
	mock := &MockBookingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBookingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingServiceInterface) EXPECT() *MockBookingServiceInterfaceMockRecorder {
	return m.recorder
}

// AddBooking mocks base method.
func (m *MockBookingServiceInterface) AddBooking(ctx context.Context, userID, showID string, seats []string) (*models.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBooking", ctx, userID, showID, seats)
	ret0, _ := ret[0].(*models.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBooking indicates an expected call of AddBooking.
func (mr *MockBookingServiceInterfaceMockRecorder) AddBooking(ctx, userID, showID, seats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBooking", reflect.TypeOf((*MockBookingServiceInterface)(nil).AddBooking), ctx, userID, showID, seats)
}

// BrowseBookings mocks base method.
func (m *MockBookingServiceInterface) BrowseBookings(ctx context.Context, bookingID, userID, showID string) ([]models.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BrowseBookings", ctx, bookingID, userID, showID)
	ret0, _ := ret[0].([]models.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BrowseBookings indicates an expected call of BrowseBookings.
func (mr *MockBookingServiceInterfaceMockRecorder) BrowseBookings(ctx, bookingID, userID, showID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BrowseBookings", reflect.TypeOf((*MockBookingServiceInterface)(nil).BrowseBookings), ctx, bookingID, userID, showID)
}
