// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "eventro2/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventServiceI is a mock of EventServiceI interface.
type MockEventServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceIMockRecorder
}

// MockEventServiceIMockRecorder is the mock recorder for MockEventServiceI.
type MockEventServiceIMockRecorder struct {
	mock *MockEventServiceI
}

// NewMockEventServiceI creates a new mock instance.
func NewMockEventServiceI(ctrl *gomock.Controller) *MockEventServiceI {
	mock := &MockEventServiceI{ctrl: ctrl}
	mock.recorder = &MockEventServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventServiceI) EXPECT() *MockEventServiceIMockRecorder {
	return m.recorder
}

// BrowseEvents mocks base method.
func (m *MockEventServiceI) BrowseEvents(ctx context.Context, filter models.EventFilter) ([]models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BrowseEvents", ctx, filter)
	ret0, _ := ret[0].([]models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BrowseEvents indicates an expected call of BrowseEvents.
func (mr *MockEventServiceIMockRecorder) BrowseEvents(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BrowseEvents", reflect.TypeOf((*MockEventServiceI)(nil).BrowseEvents), ctx, filter)
}

// CreateNewEvent mocks base method.
func (m *MockEventServiceI) CreateNewEvent(ctx context.Context, name, description, duration string, category models.EventCategory, artistIDs []string) (models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewEvent", ctx, name, description, duration, category, artistIDs)
	ret0, _ := ret[0].(models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewEvent indicates an expected call of CreateNewEvent.
func (mr *MockEventServiceIMockRecorder) CreateNewEvent(ctx, name, description, duration, category, artistIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewEvent", reflect.TypeOf((*MockEventServiceI)(nil).CreateNewEvent), ctx, name, description, duration, category, artistIDs)
}

// DeleteEvent mocks base method.
func (m *MockEventServiceI) DeleteEvent(ctx context.Context, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockEventServiceIMockRecorder) DeleteEvent(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockEventServiceI)(nil).DeleteEvent), ctx, eventID)
}

// UpdateEvent mocks base method.
func (m *MockEventServiceI) UpdateEvent(ctx context.Context, eventID string, updateData models.EventUpdate) (models.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, eventID, updateData)
	ret0, _ := ret[0].(models.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockEventServiceIMockRecorder) UpdateEvent(ctx, eventID, updateData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockEventServiceI)(nil).UpdateEvent), ctx, eventID, updateData)
}
