// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/show_service_mock.go -package=mocks -source=interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "eventro2/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockShowServiceInterface is a mock of ShowServiceInterface interface.
type MockShowServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShowServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockShowServiceInterfaceMockRecorder is the mock recorder for MockShowServiceInterface.
type MockShowServiceInterfaceMockRecorder struct {
	mock *MockShowServiceInterface
}

// NewMockShowServiceInterface creates a new mock instance.
func NewMockShowServiceInterface(ctrl *gomock.Controller) *MockShowServiceInterface {
	mock := &MockShowServiceInterface{ctrl: ctrl}
	mock.recorder = &MockShowServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowServiceInterface) EXPECT() *MockShowServiceInterfaceMockRecorder {
	return m.recorder
}

// BrowseShows mocks base method.
func (m *MockShowServiceInterface) BrowseShows(ctx context.Context, filter models.ShowFilter) ([]models.ShowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BrowseShows", ctx, filter)
	ret0, _ := ret[0].([]models.ShowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BrowseShows indicates an expected call of BrowseShows.
func (mr *MockShowServiceInterfaceMockRecorder) BrowseShows(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BrowseShows", reflect.TypeOf((*MockShowServiceInterface)(nil).BrowseShows), ctx, filter)
}

// CreateShow mocks base method.
func (m *MockShowServiceInterface) CreateShow(ctx context.Context, eventID, venueID, hostID string, price float64, showDate time.Time, showTime string) (models.ShowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShow", ctx, eventID, venueID, hostID, price, showDate, showTime)
	ret0, _ := ret[0].(models.ShowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShow indicates an expected call of CreateShow.
func (mr *MockShowServiceInterfaceMockRecorder) CreateShow(ctx, eventID, venueID, hostID, price, showDate, showTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShow", reflect.TypeOf((*MockShowServiceInterface)(nil).CreateShow), ctx, eventID, venueID, hostID, price, showDate, showTime)
}

// DeleteShow mocks base method.
func (m *MockShowServiceInterface) DeleteShow(ctx context.Context, showID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShow", ctx, showID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShow indicates an expected call of DeleteShow.
func (mr *MockShowServiceInterfaceMockRecorder) DeleteShow(ctx, showID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShow", reflect.TypeOf((*MockShowServiceInterface)(nil).DeleteShow), ctx, showID)
}

// UpdateShow mocks base method.
func (m *MockShowServiceInterface) UpdateShow(ctx context.Context, showID, userID string, update models.UpdateShowData) (models.ShowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShow", ctx, showID, userID, update)
	ret0, _ := ret[0].(models.ShowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShow indicates an expected call of UpdateShow.
func (mr *MockShowServiceInterfaceMockRecorder) UpdateShow(ctx, showID, userID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShow", reflect.TypeOf((*MockShowServiceInterface)(nil).UpdateShow), ctx, showID, userID, update)
}
