// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/show_repository_mock.go -package=mocks -source=interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "eventro2/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShowRepository is a mock of ShowRepository interface.
type MockShowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShowRepositoryMockRecorder
	isgomock struct{}
}

// MockShowRepositoryMockRecorder is the mock recorder for MockShowRepository.
type MockShowRepositoryMockRecorder struct {
	mock *MockShowRepository
}

// NewMockShowRepository creates a new mock instance.
func NewMockShowRepository(ctrl *gomock.Controller) *MockShowRepository {
	mock := &MockShowRepository{ctrl: ctrl}
	mock.recorder = &MockShowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowRepository) EXPECT() *MockShowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShowRepository) Create(show *models.Show) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", show)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShowRepositoryMockRecorder) Create(show any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShowRepository)(nil).Create), show)
}

// Delete mocks base method.
func (m *MockShowRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShowRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShowRepository)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockShowRepository) Find(filter models.ShowFilter) ([]models.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]models.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockShowRepositoryMockRecorder) Find(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockShowRepository)(nil).Find), filter)
}

// GetByID mocks base method.
func (m *MockShowRepository) GetByID(id string) (*models.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockShowRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockShowRepository)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockShowRepository) List() ([]models.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]models.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockShowRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShowRepository)(nil).List))
}

// ListByEvent mocks base method.
func (m *MockShowRepository) ListByEvent(eventID string) ([]models.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEvent", eventID)
	ret0, _ := ret[0].([]models.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEvent indicates an expected call of ListByEvent.
func (mr *MockShowRepositoryMockRecorder) ListByEvent(eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEvent", reflect.TypeOf((*MockShowRepository)(nil).ListByEvent), eventID)
}

// Update mocks base method.
func (m *MockShowRepository) Update(show *models.Show) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", show)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShowRepositoryMockRecorder) Update(show any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShowRepository)(nil).Update), show)
}
