// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/venue_repository_mock.go -package=mocks -source=interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "eventro2/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVenueRepository is a mock of VenueRepository interface.
type MockVenueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVenueRepositoryMockRecorder
	isgomock struct{}
}

// MockVenueRepositoryMockRecorder is the mock recorder for MockVenueRepository.
type MockVenueRepositoryMockRecorder struct {
	mock *MockVenueRepository
}

// NewMockVenueRepository creates a new mock instance.
func NewMockVenueRepository(ctrl *gomock.Controller) *MockVenueRepository {
	mock := &MockVenueRepository{ctrl: ctrl}
	mock.recorder = &MockVenueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVenueRepository) EXPECT() *MockVenueRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVenueRepository) Create(venue *models.Venue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", venue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVenueRepositoryMockRecorder) Create(venue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVenueRepository)(nil).Create), venue)
}

// Delete mocks base method.
func (m *MockVenueRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVenueRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVenueRepository)(nil).Delete), id)
}

// Find mocks base method.
func (m *MockVenueRepository) Find(filter models.VenueFilter) ([]models.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", filter)
	ret0, _ := ret[0].([]models.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockVenueRepositoryMockRecorder) Find(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockVenueRepository)(nil).Find), filter)
}

// GetByID mocks base method.
func (m *MockVenueRepository) GetByID(id string) (*models.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVenueRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVenueRepository)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockVenueRepository) List() ([]models.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]models.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVenueRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVenueRepository)(nil).List))
}

// ListByCity mocks base method.
func (m *MockVenueRepository) ListByCity(city string) ([]models.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCity", city)
	ret0, _ := ret[0].([]models.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCity indicates an expected call of ListByCity.
func (mr *MockVenueRepositoryMockRecorder) ListByCity(city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCity", reflect.TypeOf((*MockVenueRepository)(nil).ListByCity), city)
}

// ListByHost mocks base method.
func (m *MockVenueRepository) ListByHost(hostID string) ([]models.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByHost", hostID)
	ret0, _ := ret[0].([]models.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByHost indicates an expected call of ListByHost.
func (mr *MockVenueRepositoryMockRecorder) ListByHost(hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByHost", reflect.TypeOf((*MockVenueRepository)(nil).ListByHost), hostID)
}

// Update mocks base method.
func (m *MockVenueRepository) Update(venue *models.Venue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", venue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVenueRepositoryMockRecorder) Update(venue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVenueRepository)(nil).Update), venue)
}
