// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/venue_service_mock.go -package=mocks -source=interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "eventro2/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVenueServiceInterface is a mock of VenueServiceInterface interface.
type MockVenueServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVenueServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockVenueServiceInterfaceMockRecorder is the mock recorder for MockVenueServiceInterface.
type MockVenueServiceInterfaceMockRecorder struct {
	mock *MockVenueServiceInterface
}

// NewMockVenueServiceInterface creates a new mock instance.
func NewMockVenueServiceInterface(ctrl *gomock.Controller) *MockVenueServiceInterface {
	mock := &MockVenueServiceInterface{ctrl: ctrl}
	mock.recorder = &MockVenueServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVenueServiceInterface) EXPECT() *MockVenueServiceInterfaceMockRecorder {
	return m.recorder
}

// BrowseVenues mocks base method.
func (m *MockVenueServiceInterface) BrowseVenues(ctx context.Context, filter models.VenueFilter) ([]models.VenueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BrowseVenues", ctx, filter)
	ret0, _ := ret[0].([]models.VenueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BrowseVenues indicates an expected call of BrowseVenues.
func (mr *MockVenueServiceInterfaceMockRecorder) BrowseVenues(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BrowseVenues", reflect.TypeOf((*MockVenueServiceInterface)(nil).BrowseVenues), ctx, filter)
}

// CreateVenue mocks base method.
func (m *MockVenueServiceInterface) CreateVenue(ctx context.Context, hostID, name, city, state string, isSeatLayoutRequired bool) (models.VenueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVenue", ctx, hostID, name, city, state, isSeatLayoutRequired)
	ret0, _ := ret[0].(models.VenueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVenue indicates an expected call of CreateVenue.
func (mr *MockVenueServiceInterfaceMockRecorder) CreateVenue(ctx, hostID, name, city, state, isSeatLayoutRequired any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVenue", reflect.TypeOf((*MockVenueServiceInterface)(nil).CreateVenue), ctx, hostID, name, city, state, isSeatLayoutRequired)
}

// DeleteVenue mocks base method.
func (m *MockVenueServiceInterface) DeleteVenue(ctx context.Context, venueID, userID, userRole string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVenue", ctx, venueID, userID, userRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVenue indicates an expected call of DeleteVenue.
func (mr *MockVenueServiceInterfaceMockRecorder) DeleteVenue(ctx, venueID, userID, userRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVenue", reflect.TypeOf((*MockVenueServiceInterface)(nil).DeleteVenue), ctx, venueID, userID, userRole)
}

// UpdateVenue mocks base method.
func (m *MockVenueServiceInterface) UpdateVenue(ctx context.Context, venueID, userID, userRole string, update models.UpdateVenueData) (models.VenueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVenue", ctx, venueID, userID, userRole, update)
	ret0, _ := ret[0].(models.VenueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVenue indicates an expected call of UpdateVenue.
func (mr *MockVenueServiceInterfaceMockRecorder) UpdateVenue(ctx, venueID, userID, userRole, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVenue", reflect.TypeOf((*MockVenueServiceInterface)(nil).UpdateVenue), ctx, venueID, userID, userRole, update)
}
